// <auto-generated />
using System;
using AlzaWatchdog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlzaWatchdog.Api.Data.Migrations
{
    [DbContext(typeof(SqliteAppDbContext))]
    [Migration("20260904103522_NormaliseProducts")]
    partial class NormaliseProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AlzaWatchdog.Api.Domain.PriceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Availability")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CapturedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CouponPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlusPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "CapturedAt");

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("AlzaWatchdog.Api.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAvailability")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastCheckedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCouponPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPlusPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("IsActive", "LastCheckedAt");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AlzaWatchdog.Api.Domain.TrackedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WatchListId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WatchListId", "ProductId")
                        .IsUnique();

                    b.ToTable("TrackedItems");
                });

            modelBuilder.Entity("AlzaWatchdog.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAlzaPlus")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AlzaWatchdog.Api.Domain.WatchList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WatchLists");
                });

            modelBuilder.Entity("AlzaWatchdog.Api.Domain.PriceSnapshot", b =>
                {
                    b.HasOne("AlzaWatchdog.Api.Domain.Product", "Product")
                        .WithMany("Snapshots")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AlzaWatchdog.Api.Domain.TrackedItem", b =>
                {
                    b.HasOne("AlzaWatchdog.Api.Domain.Product", "Product")
                        .WithMany("TrackedBy")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlzaWatchdog.Api.Domain.WatchList", "WatchList")
                        .WithMany("Items")
                        .HasForeignKey("WatchListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WatchList");
                });

            modelBuilder.Entity("AlzaWatchdog.Api.Domain.WatchList", b =>
                {
                    b.HasOne("AlzaWatchdog.Api.Domain.User", "User")
                        .WithMany("Lists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlzaWatchdog.Api.Domain.Product", b =>
                {
                    b.Navigation("Snapshots");

                    b.Navigation("TrackedBy");
                });

            modelBuilder.Entity("AlzaWatchdog.Api.Domain.User", b =>
                {
                    b.Navigation("Lists");
                });

            modelBuilder.Entity("AlzaWatchdog.Api.Domain.WatchList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
